config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  
   get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get 'static_pages/home'

  get '/help', to: 'static_pages#help'
  
   get '/about', to: 'static_pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    validates(:name, presence: true, length: { maximum: 50 })
    validates(:password, 
                        presence: true,
                        length: { minimum: 6 })
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates(:email, 
                    presence: true, 
                    length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false } )
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

   def destroy
    log_out
    redirect_to root_url
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

   def new
    @user = User.new
   end
   
   def create
    @user = User.new(user_params)
    if @user.save
        lpg_in @user
      # Handle a successful save.
      flash[:success] = "Welcome to My App Designed by Feyi Oshodi!"
      redirect_to @user
    else
      render 'new'
    end
   end
   
   private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">

        <div class="navbar-header">
            <button button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" rel="home" href="#" title="Welcome to my App">
               <%= link_to image_tag("//www.google.com/favicon.ico", style: "max-width:100px; margin-top: 15%;"), root_path, id: "logo" %>
            </a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", root_path, class: "active" %></li>
              <li><%= link_to "Help", help_path %></li>
              
                  <% if logged_in? %>
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", '#' %></li>
                    </ul>
                </li>
            </ul>
            
			<form class="navbar-form navbar-right" role="search" method="get" id="searchform" action="">
				<div class="form-group">
					<input name="s" id="s" type="text" class="search-query form-control" autocomplete="off" placeholder="Search...">
				</div>
					<%= link_to "Log out", logout_path, method: "delete" %>
			</form>
			<% else %>
      <li><%= link_to "Log in", login_path %></li>
      <% end %>
		</div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="clearfix" style="clear: both;"></div>
    <br /><br /><br />
      <div class="container">
        <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

        <h1>Help</h1>
        <p>
          Get help on the Ruby on Rails Tutorial at the
          <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
          To get help on this sample app, see the
          <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
          book</a>.
        </p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<style>

    body, html{
     height: 100%;
 	background-repeat: no-repeat;
 	background-color: #d3d3d3;
 	font-family: 'Oxygen', sans-serif;
}

.main{
 	margin-top: 70px;
}

h1.title { 
	font-size: 50px;
	font-family: 'Passion One', cursive; 
	font-weight: 400; 
}

hr{
	width: 10%;
	color: #fff;
}

.form-group{
	margin-bottom: 15px;
}

label{
	margin-bottom: 15px;
}

input,
input::-webkit-input-placeholder {
    font-size: 11px;
    padding-top: 3px;
}

.main-login{
 	background-color: #fff;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);

}

.main-center{
 	margin-top: 30px;
 	margin: 0 auto;
 	max-width: 330px;
    padding: 40px 40px;

}

.login-button{
	margin-top: 5px;
}

.login-register{
	font-size: 11px;
	text-align: center;
}

</style>

<div class="container">
			<div class="row main">
				<div class="panel-heading">
	               <div class="panel-title text-center">
	               		<h1 class="title">Sign Up</h1>
	               		<hr />
	               	</div>
	            </div> 
				<div class="main-login main-center">
					<%= form_for(@user, url: signup_path) do |f| %>
					<%= render 'shared/error_messages' %>
						<div class="form-group">
						    <%= f.label :name, class: "cols-sm-2 control-label" %>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
									<%= f.text_field :name, class: "form-control", placeholder: "Enter your Name" %>
								</div>
							</div>
						</div>

						<div class="form-group">
						    <%= f.label :email, class: "cols-sm-2 control-label" %>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></span>
									<%= f.email_field :email, class: "form-control", placeholder: "Enter your Name" %>
								</div>
							</div>
						</div>

						<div class="form-group">
						    <%= f.label :password, class: "cols-sm-2 control-label" %>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-lock" aria-hidden="true"></i></span>
									<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
								</div>
							</div>
						</div>

						<div class="form-group">
						    <%= f.label :password_confirmation, "Confirmation", class: "cols-sm-2 control-label" %>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-lock" aria-hidden="true"></i></span>
									<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
								</div>
							</div>
						</div>

						<div class="form-group ">
						    <%= f.submit "Create my account", class: "btn btn-primary btn-lg btn-block login-button" %>
						</div>
						<div class="login-register">
				            <a href="index.php">Login</a>
				         </div>
					<% end %>
				</div>
			</div>
		</div>

		<script type="text/javascript" src="assets/js/bootstrap.js"></script>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>